# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160326_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='number',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='subsection',
            old_name='number',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='budget.Section'),
        ),
    ]
